### PR TITLE
add borders for each graph summary

### PR DESCRIPTION
**Pull request by osherdp**

### CODE REVIEW

**Comment by osherdp** [comment]
Screenshot from 2020-03-30 15-34-14

**Comment by avrahamshukron** [comment]
Two line between the 2 graphs is driving me nuts.
1. It does not reach to the right edge of the screen
2. It is off by one pixel in the connection to the divider between Volume and Rate

**Comment by avrahamshukron** [comment]
I would also try to remove the top border of the pPeak box. It looks funny

**Comment by osherdp** [comment]
@avrahamshukron it looks different on the screen:
2020-03-30-171617_640x480_scrot

**Pull request merged**
