### PR TITLE
WD Task: Re-implement in a more robust way

### PR DESCRIPTION
**Pull request by avrahamshukron**
The task now lives for the entire application duration, even if the
application missed checking-in in time.

Also the WD code is greatly simplified

Signed-off-by: Avi Shukron <avraham.shukron@gmail.com>

### CODE REVIEW

**Comment by avrahamshukron** [comment]
@Reznic ?

**Comment by Reznic** [comment]
> @Reznic ?

Hi,
We tried this before.
the sleeps for large amounts of times greatly reduce our fps, and sampling rate.
That was solved by using async sleep.
There is another way, by comparing timestamps in each interation,
but it's ugly, maybe heavy to add many comparisons each interval,
and also we'll have to do it twice - for the sleep in the wd driver, and the sleep in the wd task.
So unless we choose the ugly timestamp comparisons, 
we have no choice but use threads for the WD - the previous threads.Timer solution

**Comment by avrahamshukron** [comment]
That doesn't make any sense now since the WD is in its own task.
I ran the app with my changes. No lag and no FPS degredation

**Comment by Reznic** [comment]
> That doesn't make any sense now since the WD is in its own task.
> I ran the app with my changes. No lag and no FPS degredation

Ok
but we need to check on raspi.
And I recommend profiling the app with cProfile. (can be done on laptop as well)
It shows you exactly how much time each method takes.
We did it in the past, so call me if you'l have questions

**Pull request merged**
